In [1]:
import numpy as np

In [19]:
data = np.random.randn(4,5)
dataT = data.T

In [8]:
data

array([[-1.53714915,  0.63930893, -1.76599045,  1.01334894,  0.44611537],
       [-0.67014639, -1.44035728,  1.91947362, -0.6121419 , -1.26984219],
       [-0.50356059, -1.6264002 ,  0.92745041,  0.6002395 ,  0.40338698],
       [ 0.52395617, -0.06361828,  1.02756053, -2.32229701, -0.4591935 ]])

In [15]:
data[:data.shape[0]]


array([[-1.53714915,  0.63930893, -1.76599045,  1.01334894,  0.44611537],
       [-0.67014639, -1.44035728,  1.91947362, -0.6121419 , -1.26984219],
       [-0.50356059, -1.6264002 ,  0.92745041,  0.6002395 ,  0.40338698],
       [ 0.52395617, -0.06361828,  1.02756053, -2.32229701, -0.4591935 ]])

In [20]:
dataT

array([[ 0.52955113, -0.72783606,  0.87211599, -1.28890124],
       [-1.40726532,  0.99675922,  2.33550423, -1.18496487],
       [ 0.27597374,  0.92794397,  0.12062885,  0.59410295],
       [ 3.1627509 ,  1.78736601, -0.1694285 ,  0.04488526],
       [-0.41798871, -1.47371096, -2.03579296, -1.73509148]])

In [39]:
arr = np.arange(100)
print(arr[np.invert(np.logical_and(arr%3,arr%5))])
print(arr[np.invert(np.logical_and(arr%3,arr%5))].sum())


[ 0  3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50
 51 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


In [55]:
arr2 = np.arange(100)
print(arr2[(arr2%3==0)|(arr2%5 == 0)])

[ 0  3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50
 51 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]


In [45]:
hands_data = np.array([[31,43,73,79,11],[54,69,56,7,32],[56,22,41,70,42],[56,94,22,80,31]])
hands_data

array([[31, 43, 73, 79, 11],
       [54, 69, 56,  7, 32],
       [56, 22, 41, 70, 42],
       [56, 94, 22, 80, 31]])

In [54]:

print(hands_data.mean(axis = 0),'\n',hands_data.std(axis = 0))


[49.25 57.   48.   59.   29.  ] 
 [10.56823069 27.08320513 18.80159568 30.27375101 11.24722188]
